### ISSUE TITLE
Queryless parameters should be limited to one dash, not two

### ISSUE THREAD

**Issue by Jessicaward** [Jessicaward/SpotNetCore#62]
--d should be -d

**Comment by srth21** [comment]
@Jessicaward : Mind if I pick this up? In case you haven't already started working on it. Seems like a good first Issue to work on!

**Comment by Jessicaward** [comment]
Hi @srth21, yep go for it!

When finishing up with an issue, please can you create a pull request and assign it to me? :) Thanks!

**Comment by srth21** [comment]
@Jessicaward Hey yeah sure. 
Getting this error though when I try to push to a remote branch. 

remote: Permission to Jessicaward/SpotNetCore.git denied to srth21.
fatal: unable to access 'https://github.com/Jessicaward/SpotNetCore.git/': The requested URL returned error: 403

Do you have to assign some permissions?

**Comment by Jessicaward** [comment]
Ah maybe, yep I will check now.

**Comment by Jessicaward** [comment]
I have sent you an invite :)

**Comment by srth21** [comment]
Got it! Thanks. 

Also, I had a couple of issues with some Spotify related auth. 
I have pinged you on Discord, can you check once? 

Meanwhile I will raise a PR for this.
